spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 125806
    username: root
    url: jdbc:mysql://localhost:3306/npip
    jpa:
        properties:
          hibernate:
            show_sql: true
            format_sql: true
server:
  port: 1111