spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npip
    username: root
    password: 125806
    filters: stat,wall,log4j
    maxActive: 20
    InitialSize: 1
    maxWait: 60000
    poolPrepareStatement: true
    maxPoolPrepareStatementPerConnectionSize: 5000
    connectionProperties: druid,stat,mergeSql=true,druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunMillis: 60000
    minEvictableTimeMillis: 300000
    validationQuery: true
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 1111
debug: true


