server:
  port: 1122
 ## datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 125806
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=yes&characterEncoding=utf8&serverTimezone=UTC

# mybatis
mybatis:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml
